'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter, Space_Grotesk, Great_Vibes } from 'next/font/google';
import { Providers } from './providers';
import NavBar from './components/Navbar';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space',
});

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  variable: '--font-greatVibes',
  weight: '400',
});

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.variable} ${inter.variable} ${greatVibes.variable} font-sans`}
      >
        <NavBar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
